export const groups=[
  {label:'项目介绍',pages:[['introduction','这个知识库能做什么？','docs/handbook/overview.md'],['introduction/use-cases','适合谁与能力边界'],['introduction/principles','项目动机与知识治理','docs/handbook/principles.md']]},
  {label:'快速开始',pages:[['getting-started','安装与第一次校验','docs/handbook/installation.md'],['getting-started/integrate','接入 FTC 项目','docs/project-integration.md']]},
  {label:'核心概念',pages:[['concepts/rules','规则与证据'],['concepts/resolution','队伍、赛季与确定性裁决','docs/handbook/resolution.md'],['concepts/approval','候选与审批']]},
  {label:'使用指南',pages:[['guides/cli','CLI 与聊天编辑','docs/cli-agent.md'],['guides/local-web','本地网页会话'],['guides/android-studio','Android Studio 插件','docs/android-studio-plugin.md']]},
  {label:'Agent 接入',pages:[['agent/workflow','resolve → 写代码 → check'],['agent/configuration','固定版本与项目配置'],['agent/verification','安装与代码验收'],['agent/upgrades','团队协作与升级']]},
  {label:'FTC 教程',pages:[['tutorials/sdk','Android Studio 与 FTC SDK','knowledge/guides/setup/android-studio-ftc-sdk.md'],['tutorials/ftclib','FTCLib','knowledge/guides/setup/ftclib.md'],['tutorials/pedro','Pedro Pathing','knowledge/guides/tools/pedro-pathing.md'],['tutorials/pedro-verification','Pedro 示例与发布验证','docs/handbook/pedro-verification.md'],['tutorials/dashboard','FTC Dashboard','knowledge/guides/setup/ftc-dashboard.md'],['tutorials/limelight','Limelight 3A','knowledge/guides/tools/limelight-3a.md'],['tutorials/gobilda','goBILDA 电机与舵机','knowledge/guides/tools/gobilda-motors-servos.md'],['tutorials/control-hub','Control Hub 指示灯排障','knowledge/guides/debugging/control-hub-led-blink-codes.md'],['tutorials/rookiebot','RookieBot 项目实践','knowledge/guides/practices/rookiebot-tutorial.md']]},
  {label:'维护与参考',pages:[['reference/contributing','添加与维护知识','docs/handbook/contributing.md'],['reference/rule-schema','知识目录与规则字段','docs/handbook/rule-schema.md'],['reference/approval','审批规则与完整示例','docs/handbook/approval.md'],['reference/troubleshooting','常见问题','docs/handbook/troubleshooting.md'],['reference/development','架构、开发与验证','docs/handbook/development.md'],['reference/candidates','候选提取与审批','docs/candidate-extraction.md'],['reference/kernel','CLI 与 JSON 契约','docs/kernel-contract.md'],['reference/checks','检查语义与已知限制','docs/standardizer-check.md'],['reference/ci','CI 门禁'],['reference/status','版本与验证范围']]},
];
export const navigation=groups.map(group=>({label:group.label,items:group.pages.map(([slug,label])=>({slug,label}))}));
