org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
agpVersion=8.7.0
compileSdk=30
minSdk=24
ftcSdkVersion=11.2.0
ftcSdkTag=v11.2
ftcSdkCommit=4ed7c4666aec265a6fd9e674ca40462e9dfe4bf8
pedroVersion=2.1.2
pedroCommit=96df977d30329eef57c226cf1e6854026f4dfe4f
pedroQuickstartCommit=d3aea9ca3c5b4c09eded8580229b86996480ee89
