org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
agpVersion=8.7.0
compileSdk=34
minSdk=24
ftcSdkVersion=11.2.1
ftcSdkTag=v11.2.1
ftcSdkCommit=26cd1fdd2a3c4b26173d9ff33a3279c27d1c7ad1
pedroVersion=3.0.0
pedroTuningVersion=1.0.0
pedroCommit=fa5a07c7761ed01f943ef37ea29b71f30138b5d1
pedroQuickstartCommit=b4312385b7d0cc5e8dd263ec3927c9ef0cb48f36
