pluginManagement {
    repositories {
        google()
        mavenCentral()
        // Official Pedro 3 manual-install repository.
        maven { url 'https://repo.dairy.foundation/releases/' }
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.library' version providers.gradleProperty('agpVersion').get()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://repo.dairy.foundation/releases/' }
    }
}
rootProject.name='pedro-example-compile'
